### ISSUE TITLE
Error when playing game

### ISSUE THREAD

**Issue by mrfzvx12** [LoL-Human/bot-wa#5]
![Screenshot_2022-07-22-10-46-22-610_com termux](https://user-images.githubusercontent.com/72728486/180358486-8a5726d9-94f1-49c4-b900-39f42ae63e70.jpg)

**Comment by LoL-Human** [comment]
> ![Screenshot_2022-07-22-10-46-22-610_com termux](https://user-images.githubusercontent.com/72728486/180358486-8a5726d9-94f1-49c4-b900-39f42ae63e70.jpg)

maybe you can try with our new code

**Comment by HadatMTCH** [comment]
#8 

This issue has been fixed on latest code, try to pull and run again.

**Comment by mrfzvx12** [comment]
> #8
> 
> This issue has been fixed on latest code, try to pull and run again.

How to add when the answer is wrong the bot sends a message

**Comment by LoL-Human** [comment]
> 

i think it will spamming

**Comment by LoL-Human** [comment]
> > #8
> > This issue has been fixed on latest code, try to pull and run again.
> 
> How to add when the answer is wrong the bot sends a message

i think it will spamming

**Comment by mrfzvx12** [comment]
Oke close

**Comment by mrfzvx12** [comment]
![Screenshot_2022-08-10-18-53-27-731_com android chrome](https://user-images.githubusercontent.com/72728486/183894838-c187edd5-6441-43b5-b7f6-37744130337d.jpg)

When game is running.. and then someone sends a sticker/audio/video/image then it shows an error

**Comment by LoL-Human** [comment]
okay

**Comment by LoL-Human** [comment]
you can try our new code

**Comment by mrfzvx12** [comment]
> you can try our new code

it makes no response

**Comment by LoL-Human** [comment]
okay

**Comment by LoL-Human** [comment]
> > you can try our new code
> 
> it makes no response

okay done, I hope this fixed your issues
